const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate-v2');
const Schema = mongoose.Schema;
const {
    MONTHLY,
    YEARLY,
    ORDERSTATUS,
    myCustomLabels
} = require('../../config/constants/common');

mongoosePaginate.paginate.options = {
    customLabels: myCustomLabels,
};

const schema = new Schema(
    {
        subscriptionId: {
            type: Schema.Types.ObjectId,
            ref: 'subscriptions',
            index: true,
        },
        subscriptionType: { type: String, enum: [MONTHLY, YEARLY] }, // subscription type Ex. Monthly, yearly
        orderNo: { type: String }, // generated by seriesGenerator
        userId: { type: Schema.Types.ObjectId, ref: 'user', index: true },
        compId: { type: Schema.Types.ObjectId, ref: 'company', index: true },
        sts: { type: Number, default: ORDERSTATUS.PENDING, index: true }, // 1 for success, 2 for pending, 3 for failed
        subTypeNm: { type: String }, // subscription type name (plans/ topup)
        totalNoOfUser: { type: Number }, //total member
        amt: { type: Number },
        currency: { type: String, default: 'USD' },
        fees: { type: Object }, // GST and other charges
        expireAt: { type: Date, index: true },
        isActive: { type: Boolean, default: false, index: true },
        receiptNo: { type: String }, // generated by seriesGenerator,
        receiptId: { type: Schema.Types.ObjectId, ref: 'file', index: true },
        createdBy: { type: Schema.Types.ObjectId, ref: 'user' },
    },
    { timestamps: true },
);

schema.plugin(mongoosePaginate);

const order = mongoose.model('order', schema, 'order');
module.exports = order;
